### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by olmerg** [tu-darmstadt-ros-pkg/ublox#1]
if i run the command sudo apt-get install ros-indigo-ublox

it is not there

**Comment by meyerj** [comment]
This repository is not released in ROS and therefore not available as binary package. You have to build it from source.

Here are some basic tutorials from the ROS wiki for the case you don't know how to do that:
- [Installing and Configuring Your ROS Environment](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment)
- [Building and using catkin packages in a workspace](http://wiki.ros.org/catkin/Tutorials/using_a_workspace)
