### ISSUE TITLE
rosrun ublox_gps ublox_gps

### ISSUE THREAD

**Issue by vmlane** [tu-darmstadt-ros-pkg/ublox#3]
Catkin cannot find the ublox_gps executable for the ublox_gps because the CMakeLists.txt file was written improperly. Therefore, `$ rosrun ublox_gps ublox_gps` does not work. 

In the ublox_gps/CMakeLists.txt, the catkin_package command (below), is in the wrong place. It should be above 'add_library(ublox_gps SHARED src/gps.cpp)' and below `include_directories(include ${Boost_INCLUDE_DIR} ${catkin_INCLUDE_DIRS})`. As it currently is, 

```
catkin_package(
    DEPENDS boost
    CATKIN_DEPENDS roscpp ublox_msgs sensor_msgs ublox_serialization
    INCLUDE_DIRS include
    LIBRARIES ublox_gps
)
```

The attached file is a corrected version of ublock_gps/CMakeLists.txt. I can submit a pull request if you'd like.

See ROS tutorials and auto-generated CMakelists.txt files for packages for examples. 
[CMakeLists.txt](https://github.com/KumarRobotics/ublox/files/1052277/CMakeLists.txt)

**Comment by meyerj** [comment]
You are absolutely right. The package has been written for the groovy version of catkin which was different and has not been updated since then.

Your suggestions should have been applied in https://github.com/tu-darmstadt-ros-pkg/ublox/commit/7dfe99223123af2c8a86e7e504516c11fd749417 for `ublox_gps` and https://github.com/tu-darmstadt-ros-pkg/ublox/commit/595b1b8bf85ba78816bb6edfd52b6de7c07bbaed for all the other packages.

**Comment by vmlane** [comment]
Please change the link on ROS's website http://wiki.ros.org/ublox#preview.

It's currently linked to buggy code.

**Comment by meyerj** [comment]
I was not aware of the fork at https://github.com/KumarRobotics/ublox. As I will eventually need these packages again to interface a uBlox M8P receiver and therefore interested to review your changes and eventually merge them back to this repo.

> Please change the link on ROS's website http://wiki.ros.org/ublox#preview.

Which link exactly you are referring to? Feel free to update the ROS wiki yourself.

If you want to take over maintainership officially, I am fine with that. In that case please submit a PR to https://github.com/ros/rosdistro and update the indexing information in various `distribution.yaml` files. This is where the information in the package header of ROS wiki pages comes from. See [here](http://wiki.ros.org/rosdistro/Tutorials/Indexing%20Your%20ROS%20Repository%20for%20Documentation%20Generation) for details.

**Comment by vmlane** [comment]
The links are generated from the Stack Manifest, which only come from released packages, I can contact ros and Kumar Robotics about using their version instead, but I cannot do this since it is not my repo.
